---
title: 'Lab 11: Simulation and Power Analysis'
author: "Elyse McCormick"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Q1 (2 pts.): Include a figure of your line plot in your report.**

**Q2 (2 pts.): Why do you think that statistical power decreases as population dispersion increases?**

Because there's more variation. If there's a high amount of variation, then statistical power isn't centering on a mean, which indicates your data are dissimilar, ultimately decreasing your statistical power and confidence.

**Q3 (2 pts.): Include a figure of your contour plot in your report.**

**Q4 (2 pts.): Qualitatively describe the patterns you see in the contour plot. Make sure you discuss the effects of sample size and population dispersion on statistical power.**

**Q5 (5 pts.): Upload your plot as an interactive html html file. NOTE: some Mac users are not able to use RGL. You may also upload a static plot created with persp() if you can’t get RGL to work on your computer.**

**Q6 (2 pts.): Describe how you could use the information shown in your plot when designing an experiment.**