---
title: "Final R Data Analysis"
author: "Elyse McCormick"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Q1 (2 pts.): Qualitatively describe the relationship between body mass and length. Does the relationship seem linear, curved, nonexistent?**

**Q2 (2 pts.): Qualitatively describe the shapes of the histograms.Do the data appear normally-distributed? Explain why or why not.Explain why we care (or not) whether the data are normally distributed.**

**Q3 (2 pts.): Using both the histograms and normality tests, do you think the (unconditioned) body masses and body length are normally-distributed? Make sure you contrast your visual assessment of normality to the results of the numerical normality tests.**

**Q4 (2 pts.): Examine the three conditional boxplots.Describe any graphical evidence you see for body mass differences based on species and/or sex.**

**Q5 (2 pts.): What do you conclude about residual normality based on the numerical and graphical diagnostics?**

**Q6 (1 pt.): Are violations of the normality assumption equally severe for all the models?**

**Q7 (2 pts.): What is the magnitude of the mass/length relationship?**

**Q8 (2 pts.): What is the expected body length of an animal that weighs 100g?**

**Q9 (2 pts.): What is the expected body length of an animal that weighs 0g?**

**Q10 (1 pt.): What is the base level for sex?**

**Q11 (1 pt.): What is the base level for binomial?**

**Q12 (1 pt.): Which sex is heavier? How do you know?**

**Q13 (1 pt.): Which species is heavier? How do you know?**

**Q14 (1 pt.): Are sex and species significant predictors for body mass?**

**Q15 (1 pt.): Is there a significant interaction?**

**Q16 (2 pts.): Examine the p-values for the main effects (sex and species) in all four of the ANOVA tables. Does the significance level of either main effect change very much among the different models?**

**Q17 (1 pt.): Which two models have the lowest AIC?**

**Q18 (4 pts.): Which of the two models with lowest AIC scores would you select? Explain your decision based on model fit and the complexity/understanding tradeoff.**
